env:
  CIRRUS_CLONE_DEPTH: "1"
  BUILD_HOSTNAME: "cirrus-ci.org"
  RCLONECONFIG_DRIVE: ENCRYPTED[fe350d3daf2746cc54ab6196e9a498682909318891cdd4c577b63f8992f2b96e0c9892fa5e32d2dc638cead82ceb92b1]
  TG_TOKEN: ENCRYPTED[!731e8438824938461ad45a395d6e34d8ed23b42b9f0194523f7ff059a7cfece583bea3e96ba47754fd92123841478e69!]
  TG_CHAT_ID: ENCRYPTED[!15e743b8536c4b293052e985a73a5af3153bde6f31fa28c896990211b82d7aaa59b21221c7d672b290349574b7a26893!]
  WORKDIR: "/tmp"
  EMAIL: ENCRYPTED[!0e3fe551fdfff79b1605cb58f9a11d7c3f57fa41966f0bbd52dc3b6e0d680bcb627e6c87887c60f795948b72383bb27c!]
  credentials: ENCRYPTED[!276b635175a6a93011d5dc0584aea7e37d69ec476f5988220e6653daf639cea8ba68d937d3214b6279342e06d828b6b7!]

task:
  name: "Build roms"
  #only_if: $CIRRUS_REPO_OWNER == ''
  timeout_in: 110m
  container:
    image: anggit86/ubuntu:22.04
    cpu: 8
    memory: 32G

  Load-Ccache_background_script:
     - ./script/load_ccache.sh

  Sync-rom_script:
     - git config --global user.name "spesunderworld"
     - git config --global user.email "$EMAIL"
     - echo "$credentials" > ~/.git-credentials
     - git config --global credential.helper store --file=~/.git-credentials
     - ./script/sync.sh
     
  Build-rom_script:
     - ./script/building.sh
     
  Ccache-info_script:
     - set -e
     - export CCACHE_DIR=$WORKDIR/ccache
     - ccache -s

  Upload-build_script:
     - ./script/ziping.sh
