WORKDIR: "/tmp"

jobs: 
  build:
    machine:
      image: ubuntu-2204:2023.07.2
    # If running ARM, the resource class needs to be added. Omitting this defaults to amd64
    resource_class: large
    steps:
      - checkout
      # Whatever you want to do
      - run: sudo apt update && sudo apt upgrade -y
      - run: git config --global user.name "spesunderworld"
      - run: git config --global user.email "$EMAIL"
      - run: sudo apt install bc bison build-essential ccache curl flex g++-multilib gcc-multilib git git-lfs gnupg gperf imagemagick lib32ncurses5-dev lib32readline-dev lib32z1-dev liblz4-tool libncurses5 libncurses5-dev libsdl1.2-dev libssl-dev libwxgtk3.0-gtk3-dev libxml2 libxml2-utils lzop pngcrush rsync schedtool squashfs-tools xsltproc zip zlib1g-dev
      - run: ./script/sync.sh
      - run: ./script/building.sh
      - run: set -e
      - run: export CCACHE_DIR=$WORKDIR/ccache
      - run: ccache -s
