jobs: 
  build:
    machine:
      image: ubuntu-2204:2023.07.2
    # If running ARM, the resource class needs to be added. Omitting this defaults to amd64
    resource_class: arm.medium
    steps:
      - checkout
      # Whatever you want to do
      - run: sudo apt-get update && sudo apt-get install -y cowsay
      - run: cowsay Continuous Integration Rocks. 
      - run: ./script/load_ccache.sh
      - run: git config --global user.name "spesunderworld"
      - run: git config --global user.email "$EMAIL"
      - run: echo "$credentials" > ~/.git-credentials
      - run: git config --global credential.helper store --file=~/.git-credentials
      - run: ./script/sync.sh
      - run: ./script/building.sh
      - run: set -e
      - run: export CCACHE_DIR=$WORKDIR/ccache
      - run: ccache -s
      - run: ./script/ziping.sh
