WORKDIR: "/tmp"

- pipeline: "ok"
  events:
  - type: "PUSH"
    refs:
    - "refs/heads/circleci-project-setup"
  fail_on_prepare_env_warning: true
  resources: "XLARGE"

      # Whatever you want to do
      df -h
      git config --global user.name "spesunderworld"
      git config --global user.email "EMAIL@raisah.com"
      sudo apt update && sudo apt upgrade -y
      git clone https://github.com/akhilnarang/scripts
      cd scripts
      ls
      bash scripts/setup/android_build_env.sh
      ./script/sync.sh
      ./script/building.sh
      set -e
      export CCACHE_DIR=$WORKDIR/ccache
      ccache -s
