WORKDIR: "/tmp"

- pipeline: "ok"
  events:
  - type: "PUSH"
    refs:
    - "refs/heads/circleci-project-setup"
  fail_on_prepare_env_warning: true
  resources: "XLARGE"

      # Whatever you want to do
      - run: git config --global user.name "spesunderworld"
      - run: git config --global user.email "EMAIL@raisah.com"
      - run: sudo apt update && sudo apt upgrade -y
      - run: git clone https://github.com/akhilnarang/scripts
      - run: cd scripts
      - run: ls
      - run: bash scripts/setup/android_build_env.sh
      - run: ./script/sync.sh
      - run: ./script/building.sh
      - run: set -e
      - run: export CCACHE_DIR=$WORKDIR/ccache
      - run: ccache -s
