WORKDIR: "/tmp"

jobs: 
  build:
    machine:
      image: ubuntu-2204:2023.07.2
    # If running ARM, the resource class needs to be added. Omitting this defaults to amd64
    resource_class: large
    steps:
      - checkout
      # Whatever you want to do
      - run: sudo apt update && sudo apt upgrade -y
      - run: git config --global user.name "spesunderworld"
      - run: git config --global user.email "$EMAIL"
      - run: git clone https://github.com/akhilnarang/scripts
      - run: df -h
      - run: cd scripts
      - run: bash setup/android_build_env.sh
      - run: ./script/sync.sh
      - run: ./script/building.sh
      - run: set -e
      - run: export CCACHE_DIR=$WORKDIR/ccache
      - run: ccache -s
